docker: docker_ubuntu_18_04.sh
	chmod +x docker_ubuntu_18_04.sh
	./docker_ubuntu_18_04.sh

docker-compose: docker_compose_ubuntu_18_04.sh
	chmod +x docker_compose_ubuntu_18_04.sh
	./docker_compose_ubuntu_18_04.sh

all: docker docker-compose
